pipeline:
  clone:
    image: armhfplugins/git

  publish:
    image: armhfplugins/docker
    username: ${DOCKER_USER}
    email: ${DOCKER_EMAIL}
    password: ${DOCKER_PASSWORD}
    repo: armhfbuild/traefik
    tags: [ "v1.2.3", "1.2.3", "v1.2", "1.2", "morbier", "latest" ]
    build_args:
      - TRAEFIK_VERSION=1.2.3
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
